# Generated by Django 4.1.7 on 2023-05-16 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2023, 5, 16, 12, 47, 49, 973850, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
